name: Print Secret Length

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  print-secret-length:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Secret Length
      env:
        NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      run: |
        if [ -z "$NEXUS_USERNAME" ]; then
          echo "SONATYPE_NEXUS_USERNAME is not set or empty"
        else
          echo "Length of SONATYPE_NEXUS_USERNAME: ${#NEXUS_USERNAME}"
        fi
